package:
  name: lmod
  version: "6.0.24"

source:
  fn: https://github.com/TACC/Lmod/archive/6.0.24.tar.gz
  url: https://github.com/TACC/Lmod/archive/6.0.24.tar.gz
  md5: 
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - vsc-base = vsc-base:main
    #
    # Would create an entry point called vsc-base that calls vsc-base.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - luajit

  run:
    - luajit

test:
  # Python imports
  imports:
    - vsc
    - vsc.utils

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/hpcugent/vsc-base
  license: UNKNOWN
  summary: 'UNKNOWN'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
