package:
  name: vsc-install
  version: "0.9.12"

source:
  fn: vsc-install-0.9.12.tar.gz
  url: https://pypi.python.org/packages/source/v/vsc-install/vsc-install-0.9.12.tar.gz
  md5: ff9e84e6f9c766f2d6f6e2307f80c5c6
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - vsc-install = vsc-install:main
    #
    # Would create an entry point called vsc-install that calls vsc-install.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - vsc
    - vsc.install

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/hpcugent/vsc-install
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
  summary: "vsc-install provides shared setuptools functions and classes for python libraries developed by UGent's HPC group"

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
